from pyspark.sql.types import *

df_schema = StructType([
    StructField("MachineIdentifier", StringType(), nullable = True),
    StructField("ProductName", StringType(), nullable = True),
    StructField("EngineVersion", StringType(), nullable = True),
    StructField("AppVersion", StringType(), nullable = True),
    StructField("AvSigVersion", StringType(), nullable = True),
    StructField("IsBeta", IntegerType(), nullable = True),
    StructField("RtpStateBitfield", IntegerType(), nullable = True),
    StructField("IsSxsPassiveMode", IntegerType(), nullable = True),
    StructField("DefaultBrowsersIdentifier", IntegerType(), nullable = True),
    StructField("AVProductStatesIdentifier", IntegerType(), nullable = True),
    StructField("AVProductsInstalled", IntegerType(), nullable = True),
    StructField("AVProductsEnabled", IntegerType(), nullable = True),
    StructField("HasTpm", IntegerType(), nullable = True),
    StructField("CountryIdentifier", IntegerType(), nullable = True),
    StructField("CityIdentifier", IntegerType(), nullable = True),
    StructField("OrganizationIdentifier", IntegerType(), nullable = True),
    StructField("GeoNameIdentifier", IntegerType(), nullable = True),
    StructField("LocaleEnglishNameIdentifier", IntegerType(), nullable = True),
    StructField("Platform", StringType(), nullable = True),
    StructField("Processor", StringType(), nullable = True),
    StructField("OsVer", StringType(), nullable = True),
    StructField("OsBuild", IntegerType(), nullable = True),
    StructField("OsSuite", IntegerType(), nullable = True),
    StructField("OsPlatformSubRelease", StringType(), nullable = True),
    StructField("OsBuildLab", StringType(), nullable = True),
    StructField("SkuEdition", StringType(), nullable = True),
    StructField("IsProtected", IntegerType(), nullable = True),
    StructField("AutoSampleOptIn", IntegerType(), nullable = True),
    StructField("PuaMode", StringType(), nullable = True),
    StructField("SMode", IntegerType(), nullable = True),
    StructField("IeVerIdentifier", IntegerType(), nullable = True),
    StructField("SmartScreen", StringType(), nullable = True),
    StructField("Firewall", IntegerType(), nullable = True),
    StructField("UacLuaenable", IntegerType(), nullable = True),
    StructField("Census_MDC2FormFactor", StringType(), nullable = True),
    StructField("Census_DeviceFamily", StringType(), nullable = True),
    StructField("Census_OEMNameIdentifier", IntegerType(), nullable = True),
    StructField("Census_OEMModelIdentifier", IntegerType(), nullable = True),
    StructField("Census_ProcessorCoreCount", IntegerType(), nullable = True),
    StructField("Census_ProcessorManufacturerIdentifier", IntegerType(), nullable = True),
    StructField("Census_ProcessorModelIdentifier", IntegerType(), nullable = True),
    StructField("Census_ProcessorClass", StringType(), nullable = True),
    StructField("Census_PrimaryDiskTotalCapacity", DecimalType(13,0), nullable = True),
    StructField("Census_PrimaryDiskTypeName", StringType(), nullable = True),
    StructField("Census_SystemVolumeTotalCapacity", IntegerType(), nullable = True),
    StructField("Census_HasOpticalDiskDrive", IntegerType(), nullable = True),
    StructField("Census_TotalPhysicalRAM", IntegerType(), nullable = True),
    StructField("Census_ChassisTypeName", StringType(), nullable = True),
    StructField("Census_InternalPrimaryDiagonalDisplaySizeInInches", DoubleType(), nullable = True),
    StructField("Census_InternalPrimaryDisplayResolutionHorizontal", IntegerType(), nullable = True),
    StructField("Census_InternalPrimaryDisplayResolutionVertical", IntegerType(), nullable = True),
    StructField("Census_PowerPlatformRoleName", StringType(), nullable = True),
    StructField("Census_InternalBatteryType", StringType(), nullable = True),
    StructField("Census_InternalBatteryNumberOfCharges", DecimalType(20,0), nullable = True),
    StructField("Census_OSVersion", StringType(), nullable = True),
    StructField("Census_OSArchitecture", StringType(), nullable = True),
    StructField("Census_OSBranch", StringType(), nullable = True),
    StructField("Census_OSBuildNumber", IntegerType(), nullable = True),
    StructField("Census_OSBuildRevision", IntegerType(), nullable = True),
    StructField("Census_OSEdition", StringType(), nullable = True),
    StructField("Census_OSSkuName", StringType(), nullable = True),
    StructField("Census_OSInstallTypeName", StringType(), nullable = True),
    StructField("Census_OSInstallLanguageIdentifier", IntegerType(), nullable = True),
    StructField("Census_OSUILocaleIdentifier", IntegerType(), nullable = True),
    StructField("Census_OSWUAutoUpdateOptionsName", StringType(), nullable = True),
    StructField("Census_IsPortableOperatingSystem", IntegerType(), nullable = True),
    StructField("Census_GenuineStateName", StringType(), nullable = True),
    StructField("Census_ActivationChannel", StringType(), nullable = True),
    StructField("Census_IsFlightingInternal", IntegerType(), nullable = True),
    StructField("Census_IsFlightsDisabled", IntegerType(), nullable = True),
    StructField("Census_FlightRing", StringType(), nullable = True),
    StructField("Census_ThresholdOptIn", IntegerType(), nullable = True),
    StructField("Census_FirmwareManufacturerIdentifier", IntegerType(), nullable = True),
    StructField("Census_FirmwareVersionIdentifier", IntegerType(), nullable = True),
    StructField("Census_IsSecureBootEnabled", IntegerType(), nullable = True),
    StructField("Census_IsWIMBootEnabled", IntegerType(), nullable = True),
    StructField("Census_IsVirtualDevice", IntegerType(), nullable = True),
    StructField("Census_IsTouchEnabled", IntegerType(), nullable = True),
    StructField("Census_IsPenCapable", IntegerType(), nullable = True),
    StructField("Census_IsAlwaysOnAlwaysConnectedCapable", IntegerType(), nullable = True),
    StructField("Wdft_IsGamer", IntegerType(), nullable = True),
    StructField("Wdft_RegionIdentifier", IntegerType(), nullable = True),
    StructField("HasDetections", IntegerType(), nullable = True)
])

df_schema2 = StructType([
StructField("MachineIdentifier", StringType(), nullable = True),
StructField("ProductName", StringType(), nullable = True),
StructField("EngineVersion", StringType(), nullable = True),
StructField("AppVersion", StringType(), nullable = True),
StructField("AvSigVersion", StringType(), nullable = True),
StructField("IsBeta", StringType(), nullable = True),
StructField("RtpStateBitfield", StringType(), nullable = True),
StructField("IsSxsPassiveMode", StringType(), nullable = True),
StructField("DefaultBrowsersIdentifier", StringType(), nullable = True),
StructField("AVProductStatesIdentifier", StringType(), nullable = True),
StructField("AVProductsInstalled", StringType(), nullable = True),
StructField("AVProductsEnabled", StringType(), nullable = True),
StructField("HasTpm", StringType(), nullable = True),
StructField("CountryIdentifier", StringType(), nullable = True),
StructField("CityIdentifier", StringType(), nullable = True),
StructField("OrganizationIdentifier", StringType(), nullable = True),
StructField("GeoNameIdentifier", StringType(), nullable = True),
StructField("LocaleEnglishNameIdentifier", StringType(), nullable = True),
StructField("Platform", StringType(), nullable = True),
StructField("Processor", StringType(), nullable = True),
StructField("OsVer", StringType(), nullable = True),
StructField("OsBuild", StringType(), nullable = True),
StructField("OsSuite", StringType(), nullable = True),
StructField("OsPlatformSubRelease", StringType(), nullable = True),
StructField("OsBuildLab", StringType(), nullable = True),
StructField("SkuEdition", StringType(), nullable = True),
StructField("IsProtected", StringType(), nullable = True),
StructField("AutoSampleOptIn", StringType(), nullable = True),
StructField("PuaMode", StringType(), nullable = True),
StructField("SMode", StringType(), nullable = True),
StructField("IeVerIdentifier", StringType(), nullable = True),
StructField("SmartScreen", StringType(), nullable = True),
StructField("Firewall", StringType(), nullable = True),
StructField("UacLuaenable", StringType(), nullable = True),
StructField("Census_MDC2FormFactor", StringType(), nullable = True),
StructField("Census_DeviceFamily", StringType(), nullable = True),
StructField("Census_OEMNameIdentifier", StringType(), nullable = True),
StructField("Census_OEMModelIdentifier", StringType(), nullable = True),
StructField("Census_ProcessorCoreCount", StringType(), nullable = True),
StructField("Census_ProcessorManufacturerIdentifier", StringType(), nullable = True),
StructField("Census_ProcessorModelIdentifier", StringType(), nullable = True),
StructField("Census_ProcessorClass", StringType(), nullable = True),
StructField("Census_PrimaryDiskTotalCapacity", StringType(), nullable = True),
StructField("Census_PrimaryDiskTypeName", StringType(), nullable = True),
StructField("Census_SystemVolumeTotalCapacity", StringType(), nullable = True),
StructField("Census_HasOpticalDiskDrive", StringType(), nullable = True),
StructField("Census_TotalPhysicalRAM", StringType(), nullable = True),
StructField("Census_ChassisTypeName", StringType(), nullable = True),
StructField("Census_InternalPrimaryDiagonalDisplaySizeInInches", StringType(), nullable = True),
StructField("Census_InternalPrimaryDisplayResolutionHorizontal", StringType(), nullable = True),
StructField("Census_InternalPrimaryDisplayResolutionVertical", StringType(), nullable = True),
StructField("Census_PowerPlatformRoleName", StringType(), nullable = True),
StructField("Census_InternalBatteryType", StringType(), nullable = True),
StructField("Census_InternalBatteryNumberOfCharges", StringType(), nullable = True),
StructField("Census_OSVersion", StringType(), nullable = True),
StructField("Census_OSArchitecture", StringType(), nullable = True),
StructField("Census_OSBranch", StringType(), nullable = True),
StructField("Census_OSBuildNumber", StringType(), nullable = True),
StructField("Census_OSBuildRevision", StringType(), nullable = True),
StructField("Census_OSEdition", StringType(), nullable = True),
StructField("Census_OSSkuName", StringType(), nullable = True),
StructField("Census_OSInstallTypeName", StringType(), nullable = True),
StructField("Census_OSInstallLanguageIdentifier", StringType(), nullable = True),
StructField("Census_OSUILocaleIdentifier", StringType(), nullable = True),
StructField("Census_OSWUAutoUpdateOptionsName", StringType(), nullable = True),
StructField("Census_IsPortableOperatingSystem", StringType(), nullable = True),
StructField("Census_GenuineStateName", StringType(), nullable = True),
StructField("Census_ActivationChannel", StringType(), nullable = True),
StructField("Census_IsFlightingInternal", StringType(), nullable = True),
StructField("Census_IsFlightsDisabled", StringType(), nullable = True),
StructField("Census_FlightRing", StringType(), nullable = True),
StructField("Census_ThresholdOptIn", StringType(), nullable = True),
StructField("Census_FirmwareManufacturerIdentifier", StringType(), nullable = True),
StructField("Census_FirmwareVersionIdentifier", StringType(), nullable = True),
StructField("Census_IsSecureBootEnabled", StringType(), nullable = True),
StructField("Census_IsWIMBootEnabled", StringType(), nullable = True),
StructField("Census_IsVirtualDevice", StringType(), nullable = True),
StructField("Census_IsTouchEnabled", StringType(), nullable = True),
StructField("Census_IsPenCapable", StringType(), nullable = True),
StructField("Census_IsAlwaysOnAlwaysConnectedCapable", StringType(), nullable = True),
StructField("Wdft_IsGamer", StringType(), nullable = True),
StructField("Wdft_RegionIdentifier", StringType(), nullable = True),
StructField("HasDetections", StringType(), nullable = True)
])

different_values = {
    "MachineIdentifier": 8921483,
    "ProductName": 6,
    "EngineVersion": 70,
    "AppVersion": 110,
    "AvSigVersion": 8531,
    "IsBeta": 2,
    "RtpStateBitfield": 8,
    "IsSxsPassiveMode": 2,
    "DefaultBrowsersIdentifier": 2018,
    "AVProductStatesIdentifier": 28971,
    "AVProductsInstalled": 9,
    "AVProductsEnabled": 7,
    "HasTpm": 2,
    "CountryIdentifier": 222,
    "CityIdentifier": 107367,
    "OrganizationIdentifier": 50,
    "GeoNameIdentifier": 293,
    "LocaleEnglishNameIdentifier": 276,
    "Platform": 4,
    "Processor": 3,
    "OsVer": 58,
    "OsBuild": 76,
    "OsSuite": 14,
    "OsPlatformSubRelease": 9,
    "OsBuildLab": 664,
    "SkuEdition": 8,
    "IsProtected": 3,
    "AutoSampleOptIn": 2,
    "PuaMode": 3,
    "SMode": 3,
    "IeVerIdentifier": 304,
    "SmartScreen": 22,
    "Firewall": 3,
    "UacLuaenable": 12,
    "Census_MDC2FormFactor": 13,
    "Census_DeviceFamily": 3,
    "Census_OEMNameIdentifier": 3833,
    "Census_OEMModelIdentifier": 175366,
    "Census_ProcessorCoreCount": 46,
    "Census_ProcessorManufacturerIdentifier": 8,
    "Census_ProcessorModelIdentifier": 3429,
    "Census_ProcessorClass": 4,
    "Census_PrimaryDiskTotalCapacity": 5736,
    "Census_PrimaryDiskTypeName": 5,
    "Census_SystemVolumeTotalCapacity": 536849,
    "Census_HasOpticalDiskDrive": 2,
    "Census_TotalPhysicalRAM": 3447,
    "Census_ChassisTypeName": 53,
    "Census_InternalPrimaryDiagonalDisplaySizeInInches": 786,
    "Census_InternalPrimaryDisplayResolutionHorizontal": 2181,
    "Census_InternalPrimaryDisplayResolutionVertical": 1561,
    "Census_PowerPlatformRoleName": 11,
    "Census_InternalBatteryType": 80,
    "Census_InternalBatteryNumberOfCharges": 41089,
    "Census_OSVersion": 469,
    "Census_OSArchitecture": 3,
    "Census_OSBranch": 32,
    "Census_OSBuildNumber": 165,
    "Census_OSBuildRevision": 285,
    "Census_OSEdition": 33,
    "Census_OSSkuName": 30,
    "Census_OSInstallTypeName": 9,
    "Census_OSInstallLanguageIdentifier": 40,
    "Census_OSUILocaleIdentifier": 147,
    "Census_OSWUAutoUpdateOptionsName": 6,
    "Census_IsPortableOperatingSystem": 2,
    "Census_GenuineStateName": 5,
    "Census_ActivationChannel": 6,
    "Census_IsFlightingInternal": 3,
    "Census_IsFlightsDisabled": 3,
    "Census_FlightRing": 10,
    "Census_ThresholdOptIn": 3,
    "Census_FirmwareManufacturerIdentifier": 713,
    "Census_FirmwareVersionIdentifier": 50495,
    "Census_IsSecureBootEnabled": 2,
    "Census_IsWIMBootEnabled": 3,
    "Census_IsVirtualDevice": 3,
    "Census_IsTouchEnabled": 2,
    "Census_IsPenCapable": 2,
    "Census_IsAlwaysOnAlwaysConnectedCapable": 3,
    "Wdft_IsGamer": 3,
    "Wdft_RegionIdentifier": 16
}

default_values = {
    StringType(): "unknown",
    IntegerType(): -1,
    DecimalType(13,0): -1,
    DecimalType(20,0): -1,
    DoubleType(): -1
}


